name: github pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: avsm/setup-ocaml@v3
        with:
          ocaml-compiler: '5.3'
          dune-cache: true
          allow-prerelease-opam: true

      - run: opam pin -n .
      - run: opam depext -yt calculon calculon-web
      - run: opam install -d . --deps-only
      - run: opam install odig

      - run: opam exec -- odig odoc --cache-dir=_doc/ calculon calculon-web

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_doc/_html/
          destination_dir: .
          enable_jekyll: false
